# Generated by Django 5.1.7 on 2025-03-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='printing_type',
            field=models.CharField(blank=True, choices=[('color', 'ألوان'), ('black', 'أبيض وأسود')], max_length=10, null=True, verbose_name='نوع الطباعة'),
        ),
    ]
