# Generated by Django 5.1.7 on 2025-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_printorder_printing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printorder',
            name='paper_size',
            field=models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3')], max_length=10, null=True, verbose_name='حجم الورق'),
        ),
        migrations.AlterField(
            model_name='printorder',
            name='pay',
            field=models.CharField(blank=True, choices=[('cash', 'كاش'), ('vod-cash', 'محفظة إلكترونية')], max_length=10, null=True, verbose_name='طريقة الدفع'),
        ),
    ]
